name: Continuous Deployment to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  all:
    name: Deploy all
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: decrypt
        env:
          CLOUDFLARE_ED25519: ${{ secrets.CLOUDFLARE_ED25519 }}
        run: |
          mkdir ~/.ssh && chmod 700 ~/.ssh
          echo "$CLOUDFLARE_ED25519" > ~/.ssh/cloudflare_ed25519
          chmod 600 ~/.ssh/cloudflare_ed25519
          cat > ~/.ssh/config <<EOF
          Host hyperscalar.pages.dev
              HostName github.com
              Port 22
              User git
              IdentityFile ~/.ssh/cloudflare_ed25519
          EOF
          chmod 644 ~/.ssh/config

      - name: config
        run: |
          export TZ=Asia/Shanghai
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global core.quotepath off

      - name: clone
        uses: actions/checkout@v4

      - name: status
        run: git status

      - name: pull
        run: |
          git remote add cloudflare git@hyperscalar.pages.dev:hyperscalar/hyperscalar.pages.dev.git
          git subtree add --prefix=root/public/ cloudflare master --squash

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          check-latest: true
          cache: 'npm'
          cache-dependency-path: |
            en/package-lock.json
            zh/package-lock.json

      - name: install
        run: npm install -g npm@latest

      - name: root
        run: |
          cd root
          rm -rf public/
          cp -r source public/
          cd public
          sed -i 's|https://hyperscalar.github.io|https://hyperscalar.pages.dev|g' robots.txt README.md
          sed -i 's|G-YWP460XJG2|G-JQKEN3QFD6|g' index.html
          sed -i 's|4e14621546db499aa0130cd3f9f308d7|e454ebd4f90d429da0846b70835091da|g' index.html
          sed -i 's|plm26dh6lw|plm2juu09c|g' index.html
          cd ..
          cd ..

      - name: en
        run: |
          cd en
          sed -i 's|https://hyperscalar.github.io|https://hyperscalar.pages.dev|g' _config.yml _config.next.yml source/README.md
          sed -i 's|Ov23liWoexYmK0wyIrMq|Ov23liO8ymYEEB5J8ImW|g' _config.next.yml
          sed -i 's|e97273e536b143c7d3d15293e19239f18d86929c|97b9cf715c6cf1783615ee31dc5b04116e857eca|g' _config.next.yml
          sed -i 's|G-YWP460XJG2|G-JQKEN3QFD6|g' _config.next.yml
          sed -i 's|4e14621546db499aa0130cd3f9f308d7|e454ebd4f90d429da0846b70835091da|g' _config.next.yml
          sed -i 's|plm26dh6lw|plm2juu09c|g' _config.next.yml
          npm install
          npm run build
          mv public ../root/public/en/
          cd ..

      - name: zh
        run: |
          cd zh
          sed -i 's|https://hyperscalar.github.io|https://hyperscalar.pages.dev|g' _config.yml _config.next.yml source/README.md
          sed -i 's|Ov23liPbXqUqmpgi6LQU|Ov23li5LC4fjn6mD8omR|g' _config.next.yml
          sed -i 's|1b7a6b5074e104496a902cf5279e1e1e1b2e6fbc|4da5bc4d6ebae49e5fd9a9e39f0df9e7bd5b91b8|g' _config.next.yml
          sed -i 's|G-YWP460XJG2|G-JQKEN3QFD6|g' _config.next.yml
          sed -i 's|4e14621546db499aa0130cd3f9f308d7|e454ebd4f90d429da0846b70835091da|g' _config.next.yml
          sed -i 's|plm26dh6lw|plm2juu09c|g' _config.next.yml
          npm install
          npm run build
          mv public ../root/public/zh/
          cd ..

      - name: push
        run: |
          git add -f root/public/
          git commit --allow-empty -m "Deployed by GitHub Actions"
          git subtree split --prefix=root/public/ --branch cloudflare
          git subtree push --prefix=root/public/ cloudflare master
